---
vesrion: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: admin@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  server:
    image: anildoc143/nodejs-server:v1
    ports:
      - "1111:80"
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  client:
    image: anildoc143/react-client:v1
    ports:
      - "1112:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - server

volumes:
  db_data:
  app:
  client: